version: "3.9"

services:
  db:
    image: postgres:15
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - "pg_data:/var/lib/postgresql/data"
    command:
      - "postgres"
      - "-c"
      - "log_statement=all"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
      - WAL_LEVEL=logical
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 1s
      retries: 5

volumes:
  pg_data:
