name: buf-push
on:
  push:
    branches:
      - master
permissions:
  contents: read

jobs:
  frontend_lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ui
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: 'ui/package-lock.json'
      - name: Install dependencies
        run: npm ci
      - name: Run prettier
        run: |-
          npx prettier --check 'src/**/*.{js,ts,tsx,json,css,md}'
      - name: Run eslint
        run: |-
          npx eslint 'src/**/*.{js,ts,tsx,json}'

  golangci_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3

  proto:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bufbuild/buf-setup-action@v1
      - uses: bufbuild/buf-lint-action@v1
      - uses: bufbuild/buf-breaking-action@v1
        with:
          # The 'master' branch of the GitHub repository that defines the module.
          against: "https://github.com/${GITHUB_REPOSITORY}.git#branch=master,ref=HEAD~1"
      - uses: bufbuild/buf-push-action@v1
        with:
          input: internal/proto
          buf_token: ${{ secrets.BUF_TOKEN }}
