name: release
on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: 'ui/package-lock.json'
      - name: Install frontend dependencies
        run: npm ci
        working-directory: ui
      - name: Build static assets
        run: npm run build
        working-directory: ui
      - uses: wangyoucao577/go-release-action@v1.33
        with:
          project_path: 'cmd/app/'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: linux
          goarch: amd64
